codecov:
  allow_coverage_offsets: true
  notify:
    wait_for_ci: false

coverage:
  precision: 1
  round: down
  range: "70...100"

  status:
    project:
      default: false
      linux:
        target: auto
        threshold: 1%
        if_ci_failed: error
        if_not_found: success
        flags:
          - linux-1.16
          - linux-1.17-rc
    patch:
      default: false
      linux:
        only_pulls: true
        target: 50%
        threshold: 10%
        if_ci_failed: error
        if_not_found: failure
        flags:
          - linux-1.16
          - linux-1.17-rc
    changes:
      default:
        if_ci_failed: error
        if_not_found: success
        only_pulls: false
        branches:
          - main

flags:
  linux-1.16:
    paths:
      - /
    carryforward: true
  linux-1.17-rc:
    paths:
      - /
    carryforward: true

comment:
  behavior: default
  show_carryforward_flags: true
  require_changes: true

github_checks:
  annotations: true
