run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs: []
  skip-dirs-use-default: true
  skip-files: []
  allow-parallel-runners: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true

linters-settings:
  dupl:
    threshold: 100
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude: .errcheckignore
  funlen:
    lines: 100
    statements: 60
  gocognit:
    min-complexity: 20
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - commentedOutCode
      - whyNoLint
    settings:
      hugeParam:
        sizeThreshold: 80
      rangeExprCopy:
        sizeThreshold: 512
      rangeValCopy:
        sizeThreshold: 128
  gocyclo:
    min-complexity: 15
  godot:
    scope: declarations
    capital: false
  gofmt:
    simplify: true
  goimports:
    local-prefixes: go.lsp.dev/jsonrpc2,go.lsp.dev
  golint:
    min-confidence: 0.3
  govet:
    enable-all: true
    check-shadowing: true
  depguard:
    list-type: blacklist
    include-go-root: true
    # packages-with-error-message:
    #   - github.com/sirupsen/logrus: "logging is allowed only by logutils.Log"
  lll:
    line-length: 120
    tab-width: 1
  maligned:
    suggest-new: true
  misspell:
    locale: US
    ignore-words:
      - cancelled
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true
    for-loops: true
  testpackage:
    skip-regexp: '.*(export)_test\.go'
  unparam:
    check-exported: true
    algo: cha
  unused:
    check-exported: false
  whitespace:
    multi-if: true
    multi-func: true

linters:
  fast: false
  disabled:
    - exhaustivestruct  # Checks if all struct's fields are initialized
    - forbidigo         # Forbids identifiers
    - gci               # Gci control golang package import order and make it always deterministic.
    - gochecknoglobals  # check that no global variables exist
    - gochecknoinits    # Checks that no init functions are present in Go code
    - godox             # Tool for detection of FIXME, TODO and other comment keywords
    - goerr113          # Golang linter to check the errors handling expressions
    - gofumpt           # Gofumpt checks whether code was gofumpt-ed.
    - goheader          # Checks is file header matches to pattern
    - gomnd             # An analyzer to detect magic numbers.
    - gomodguard        # Allow and block list linter for direct Go module dependencies.
    - gosec             # Inspects source code for security problems
    - nlreturn          # nlreturn checks for a new line before return and branch statements to increase code clarity
    - paralleltest      # paralleltest detects missing usage of t.Parallel() method in your Go test
    - scopelint         # Scopelint checks for unpinned variables in go programs
    - sqlclosecheck     # Checks that sql.Rows and sql.Stmt are closed.
    - testpackage
    - wsl               # Whitespace Linter
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - golint
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll               # Reports long lines
    - makezero
    - maligned
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - wrapcheck

issues:
  max-same-issues: 0
  exclude-use-default: true
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - funlen
        - gocognit
        - goconst
        - gocyclo
        - lll
        - maligned
        - wrapcheck
    - path: "(.*)?_example_test.go"
      linters:
        - gocritic
    # `TestMain` function is no longer required to call `os.Exit` since Go 1.15.
    # ref: https://golang.org/doc/go1.15#testing
    - text: "SA3000:"
      linters:
        - staticcheck
    # Exclude shadow checking on the variable named err
    - text: "shadow: declaration of \"(err|ok)\""
      linters:
        - govet
    # fake implements
    - path: fake/fake.go
      linters:
        - errcheck
    # future use
    - path: jsonrpc2.go
      linters:
        - deadcode
        - unused
        - varcheck
      text: "`(reqWaiting|reqDone)` is unused"
    # future use
    - linters:
        - deadcode
        - unused
        - varcheck
      text: "`(codeServerErrorStart|codeServerErrorEnd)` is unused"
    # goroutine
    - path: handler.go
      text: "Error return value of `handler` is not checked"
