version: 2.1

orbs:
  golang: cci-orb/golang@volatile    # https://circleci.com/orbs/registry/orb/cci-orb/golang
  codecov: codecov/codecov@volatile  # https://circleci.com/orbs/registry/orb/codecov/codecov

jobs:
  test:
    executor:
      name: golang/linux
      tag: "1.15-buster"
    working_directory: /go/src/go.lsp.dev/jsonrpc2
    parallelism: 2
    steps:
      - checkout
      - golang/gomod
      - run:
          name: Check versions
          command: |
            go version
            go env
      - run:
          name: Test and collect coverages
          command: |
            make tools
            mkdir -p /tmp/test-results
            make $(circleci tests split .circleci/coverage-targets)
          environment:
            GOTESTSUM_JSONFILE: "/tmp/test-results/unit-test.xml"
      - codecov/upload:
          file: "coverage.out"
          flags: $(if [ $CIRCLE_NODE_INDEX == 0 ]; then echo "json"; else echo "gojay"; fi)
      - store_test_results:
          path: /tmp/test-results

  lint:
    executor:
      name: golang/linux
      tag: "1.15-buster"
    working_directory: /go/src/go.lsp.dev/jsonrpc2
    parallelism: 2
    steps:
      - checkout
      - golang/gomod
      - run:
          name: Check versions
          command: |
            go version
            go env
      - run:
          name: Run lint for sources
          command: |
            make lint GO_LINT_FLAGS=$(circleci tests split .circleci/lint-buildtags)

workflows:
  version: 2
  workflows:
    jobs:
      - test:
          context: org-global
      - lint:
          context: org-global
