version: 2.1

orbs:
  golang: cci-orb/golang@volatile
  codecov: codecov/codecov@volatile

defaults: &defaults
  working_directory: /go/src/github.com/go-language-server/jsonrpc2
  executor: golang/stretch
  environment:
    GO111MODULE: "on"
    GOPROXY: "https://proxy.golang.org"
    GOSUMDB: "sum.golang.org"

jobs:
  test:
    <<: *defaults
    parallelism: 2
    steps:
      - checkout
      - golang/gomod
      - run:
          name: Test and collect coverages
          command: |
            make $(circleci tests split .circleci/coverage-targets)
      - codecov/upload:
          file: "/tmp/ci/artifacts/coverage.out"
          flags: $(if [ $CIRCLE_NODE_INDEX == 0 ]; then echo "json"; else echo "gojay"; fi)
      - store_artifacts:
          path: /tmp/ci/artifacts
      - store_artifacts:
          path: /tmp/ci/artifacts
      - store_test_results:
          path: /tmp/ci/test-results

  lint:
    <<: *defaults
    parallelism: 2
    steps:
      - checkout
      - golang/gomod
      - run:
          name: Run lint for sources
          command: |
            make lint GO_LINT_FLAGS=$(circleci tests split .circleci/lint-buildtags)

workflows:
  version: 2
  workflows:
    jobs:
      - test:
          context: org-global
      - lint:
          context: org-global
