version: 2.1

orbs:
  golang: cci-orb/golang@volatile
  codecov: codecov/codecov@volatile

jobs:
  test:
    executor:
      name: golang/buster
      tag: "1.14-buster"
    working_directory: /go/src/go.lsp.dev/jsonrpc2
    environment:
      GO111MODULE: "on"
    parallelism: 2
    steps:
      - checkout
      - golang/gomod
      - run:
          name: Test and collect coverages
          command: |
            make $(circleci tests split .circleci/coverage-targets)
      - codecov/upload:
          file: "/tmp/ci/artifacts/coverage.out"
          flags: $(if [ $CIRCLE_NODE_INDEX == 0 ]; then echo "json"; else echo "gojay"; fi)
      - store_artifacts:
          path: /tmp/ci/artifacts
      - store_artifacts:
          path: /tmp/ci/artifacts
      - store_test_results:
          path: /tmp/ci/test-results

  lint:
    executor:
      name: golang/buster
      tag: "1.14-buster"
    working_directory: /go/src/go.lsp.dev/jsonrpc2
    environment:
      GO111MODULE: "on"
    parallelism: 2
    steps:
      - checkout
      - golang/gomod
      - run:
          name: Run lint for sources
          command: |
            make lint GO_LINT_FLAGS=$(circleci tests split .circleci/lint-buildtags)

workflows:
  version: 2
  workflows:
    jobs:
      - test:
          context: org-global
      - lint:
          context: org-global
